### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [anabastos/naruto-theme#5]
Hi everyone.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by anabastos** [comment]
Hello! 
Our user base is almost none but sure it is active!

**Comment by ghost** [comment]
Hi anabastos.

> Hello!
> Our user base is almost none but sure it is active!

Thank you for answering my question, I will help as I can this project!

*Have a great day and thank you for your patience in answering my question. I'm going to close this issue since my question has been answered.*
